services:

  Shared.ConnectionManager:
    factory:
      class: ../../../modules/Shared/infrastructure/persistence/typeorm/TypeormConnectionFactory
      method: 'create'
    arguments: ['chat', '@Shared.DbConfig']

  Shared.Logger:
    class: ../../../modules/Shared/infrastructure/WinstonLogger
    arguments: []

  Shared.CommandBus:
    class: ../../../modules/Shared/infrastructure/commandBus/InMemoryCommandBus
    arguments: ['@Shared.CommandHandlersInformation']

  Shared.CommandHandlersInformation:
    class: ../../../modules/Shared/infrastructure/commandBus/CommandHandlersInformation
    arguments: ['!tagged commandHandler']

  Shared.QueryBus:
    class: ../../../modules/Shared/infrastructure/queryBus/InMemoryQueryBus
    arguments: ['@Shared.QueryHandlersInformation']

  Shared.QueryHandlersInformation:
    class: ../../../modules/Shared/infrastructure/queryBus/QueryHandlersInformation
    arguments: ['!tagged queryHandler']
  
  Shared.DbConfig:
    factory:
      class: ../../../modules/Shared/infrastructure/persistence/DbConfig
      method: 'createConfig'